# Generated by Django 5.1.3 on 2024-11-21 12:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0002_alter_informacaoenvio_num_regiao_envio'),
        ('perfil', '0002_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_produto', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.FloatField()),
                ('estoque', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='CarrinhoDeCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itens', models.JSONField(default=dict, help_text="Estrutura: {'produto_id': {'nome': str, 'descricao': str, 'preco': float, 'quantidade': int}}")),
                ('total', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('F', 'Finalizado')], default='A', max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos', to='perfil.perfil')),
                ('frete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos_envio', to='pedidos.informacaoenvio')),
            ],
            options={
                'verbose_name': 'Carrinho de Compras',
                'verbose_name_plural': 'Carrinhos de Compras',
            },
        ),
    ]
